#line 2 "pllolcode_scan.c"

#line 4 "pllolcode_scan.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pllolcode_yy_create_buffer
#define yy_delete_buffer pllolcode_yy_delete_buffer
#define yy_flex_debug pllolcode_yy_flex_debug
#define yy_init_buffer pllolcode_yy_init_buffer
#define yy_flush_buffer pllolcode_yy_flush_buffer
#define yy_load_buffer_state pllolcode_yy_load_buffer_state
#define yy_switch_to_buffer pllolcode_yy_switch_to_buffer
#define yyin pllolcode_yyin
#define yyleng pllolcode_yyleng
#define yylex pllolcode_yylex
#define yylineno pllolcode_yylineno
#define yyout pllolcode_yyout
#define yyrestart pllolcode_yyrestart
#define yytext pllolcode_yytext
#define yywrap pllolcode_yywrap
#define yyalloc pllolcode_yyalloc
#define yyrealloc pllolcode_yyrealloc
#define yyfree pllolcode_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE pllolcode_yyrestart(pllolcode_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int pllolcode_yyleng;

extern FILE *pllolcode_yyin, *pllolcode_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pllolcode_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up pllolcode_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via pllolcode_yyrestart()), so that the user can continue scanning by
	 * just pointing pllolcode_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when pllolcode_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int pllolcode_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow pllolcode_yywrap()'s to do buffer switches
 * instead of setting up a fresh pllolcode_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void pllolcode_yyrestart (FILE *input_file  );
void pllolcode_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE pllolcode_yy_create_buffer (FILE *file,int size  );
void pllolcode_yy_delete_buffer (YY_BUFFER_STATE b  );
void pllolcode_yy_flush_buffer (YY_BUFFER_STATE b  );
void pllolcode_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void pllolcode_yypop_buffer_state (void );

static void pllolcode_yyensure_buffer_stack (void );
static void pllolcode_yy_load_buffer_state (void );
static void pllolcode_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER pllolcode_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE pllolcode_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE pllolcode_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE pllolcode_yy_scan_bytes (yyconst char *bytes,int len  );

void *pllolcode_yyalloc (yy_size_t  );
void *pllolcode_yyrealloc (void *,yy_size_t  );
void pllolcode_yyfree (void *  );

#define yy_new_buffer pllolcode_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        pllolcode_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pllolcode_yy_create_buffer(pllolcode_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        pllolcode_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pllolcode_yy_create_buffer(pllolcode_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *pllolcode_yyin = (FILE *) 0, *pllolcode_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int pllolcode_yylineno;

int pllolcode_yylineno = 1;

extern char *pllolcode_yytext;
#define yytext_ptr pllolcode_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up pllolcode_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	pllolcode_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[317] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   77,   75,
       74,   73,    1,   75,   73,   71,   70,   60,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   56,   75,   75,   75,   75,   75,   72,
        6,    4,    5,    3,    9,    8,   13,   12,   13,   74,
       73,   71,   70,   69,   69,   32,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,    0,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,    0,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,    2,    0,

       69,   69,   69,   69,    7,   69,   69,   69,   69,   69,
       69,   69,   69,   14,    0,    0,   69,    0,   55,   69,
       18,   69,   69,   69,   69,    0,   69,   36,   69,    0,
       69,   47,   49,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   23,   69,   69,    0,   69,    0,    0,    0,
        0,   69,   69,   69,   69,   69,   69,   24,   69,   69,
       51,    0,    0,    0,   20,    0,   69,   58,   69,   40,
        0,    0,   65,   69,   69,    0,   10,   69,   69,   69,
       69,   69,   69,    0,   69,   69,   69,    0,   48,    0,
       64,    0,   11,    0,    0,   69,    0,   17,    0,   69,

       69,   69,   69,   69,    0,    0,    0,    0,   69,   46,
        0,    0,   69,   69,   62,    0,   69,   69,   69,   69,
       69,   69,    0,   61,   69,   69,    0,    0,    0,   37,
       38,    0,    0,    0,    0,   69,   69,   69,    0,   66,
        0,    0,    0,    0,   69,   29,   45,   19,   63,   43,
       50,    0,   69,   69,   69,   39,   25,   69,   69,   35,
       44,    0,    0,   33,    0,   26,   69,    0,   69,    0,
       54,    0,    0,    0,   15,    0,   69,   69,    0,   16,
       21,   68,   30,    0,   42,    0,   69,   57,   52,    0,
       59,    0,    0,   69,    0,   41,   34,   22,    0,    0,

        0,    0,   31,    0,    0,   27,    0,   53,    0,   28,
        0,    0,    0,    0,   67,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    1,
        1,    1,    6,    7,    6,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        1,    1,   10,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
        1,   37,    1,    1,   38,    1,   20,   20,   20,   20,

       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[39] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    3
    } ;

static yyconst flex_int16_t yy_base[322] =
    {   0,
        0,  343,   36,   37,  342,  341,   40,   41,  343,  347,
       43,   43,  347,   40,   48,   44,   48,   36,   42,    0,
       44,   35,   51,   45,  331,   61,  311,  315,   67,   52,
       75,  311,  307,    0,   58,  309,  317,   82,   69,   92,
      347,  347,  347,    0,  347,  347,  347,  347,  313,   64,
       93,   94,   96,    0,  312,  298,  315,  301,  297,  317,
      312,  297,  313,  306,  293,  300,  306,  302,  302,  315,
      302,  313,  280,  297,  297,  298,  300,  300,  296,  104,
      286,  280,  277,  293,  288,  274,  278,  277,   98,  278,
      275,  270,  270,  273,  272,  279,   82,  290,  347,  279,

      288,  287,  273,  271,    0,  257,  271,  268,  270,  262,
      259,  259,  256,    0,  269,   92,  254,  254,    0,  243,
        0,  255,  263,  239,  269,  239,  259,  251,  257,  246,
      234,    0,  233,  235,  250,  234,  240,  236,  256,  234,
      239,  233,    0,  252,  245,  226,  229,  220,  223,  225,
      224,  220,  243,  229,  109,  230,  218,    0,  229,  227,
        0,  212,  216,  208,    0,  213,  225,    0,  221,    0,
      210,  223,    0,  220,  103,  197,    0,  201,  219,  198,
      210,  205,  197,  200,  208,  211,  203,  196,  347,  198,
        0,  208,  347,  202,  201,  212,   90,    0,  190,  195,

      185,  182,  207,  192,  205,  204,  177,  173,  170,    0,
      188,  184,  187,  173,    0,  190,  183,  194,  176,  165,
      167,  176,  177,    0,  170,  167,  174,  154,  160,  347,
      347,  162,  170,  174,  168,  159,  178,  162,  145,    0,
      168,  143,  147,  172,  160,  347,  347,    0,    0,  347,
        0,  160,  143,  148,  167,    0,  347,  155,  152,  347,
      347,  132,  151,  347,  151,  347,  135,  139,  138,  134,
      347,  133,  149,  148,    0,  147,  153,  126,  130,    0,
        0,  347,  347,  131,    0,  137,  128,  347,  347,  147,
      347,  120,  123,  132,  119,  347,  347,    0,   98,  121,

      114,  103,  347,   99,  114,  347,  109,  347,   93,  347,
      101,  100,  101,   88,  347,  347,  137,  140,  143,  113,
      146
    } ;

static yyconst flex_int16_t yy_def[322] =
    {   0,
      316,    1,  317,  317,  318,  318,  319,  319,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  316,
      316,  316,  316,  321,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  316,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  316,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  316,  316,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  316,  316,  320,  316,  320,  320,
      320,  320,  320,  320,  320,  316,  320,  320,  320,  316,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  316,  320,  316,  316,  316,
      316,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  316,  316,  316,  320,  316,  320,  320,  320,  320,
      316,  316,  320,  320,  320,  316,  320,  320,  320,  320,
      320,  320,  320,  316,  320,  320,  320,  316,  316,  316,
      320,  316,  316,  316,  316,  320,  316,  320,  316,  320,

      320,  320,  320,  320,  316,  316,  316,  316,  320,  320,
      316,  316,  320,  320,  320,  316,  320,  320,  320,  320,
      320,  320,  316,  320,  320,  320,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  320,  320,  320,  316,  320,
      316,  316,  316,  316,  320,  316,  316,  320,  320,  316,
      320,  316,  320,  320,  320,  320,  316,  320,  320,  316,
      316,  316,  316,  316,  316,  316,  320,  316,  320,  316,
      316,  316,  316,  316,  320,  316,  320,  320,  316,  320,
      320,  316,  316,  316,  320,  316,  320,  316,  316,  316,
      316,  316,  316,  320,  316,  316,  316,  320,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,    0,  316,  316,  316,  316,
      316
    } ;

static yyconst flex_int16_t yy_nxt[386] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   10,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   20,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       20,   37,   38,   20,   39,   20,   10,   10,   42,   42,
       43,   43,   48,   48,   50,   51,   50,   52,   53,   51,
       51,   52,   52,   62,   51,   52,   53,   55,   60,   56,
       57,   64,   61,   66,   69,   50,   58,   50,   63,   49,
       49,   59,   44,   44,   67,   65,   80,   76,   82,   97,
       89,   77,   81,   70,   71,  146,   83,   78,   90,   72,
       73,   79,   93,   84,   51,   51,   98,   85,   51,   51,

       94,   52,   52,   52,   53,   86,   95,  126,  137,  147,
      163,   96,  199,  214,  233,   54,  164,  315,  234,  314,
      313,  312,  138,  311,  310,  309,  308,  307,  127,  306,
      215,  305,  304,  128,  303,  302,  200,   41,   41,   41,
       45,   45,   45,   47,   47,   47,   99,  301,   99,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,

      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  145,  144,  143,  142,  141,  140,

      139,  136,  135,  134,  133,  132,  131,  130,  129,  125,
      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   92,   91,   88,   87,   75,
       74,   68,  316,   46,   46,   40,    9,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316
    } ;

static yyconst flex_int16_t yy_chk[386] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        3,    4,    7,    8,   11,   12,   11,   14,   14,   12,
       15,   16,   16,   22,   15,   17,   17,   18,   21,   18,
       19,   23,   21,   24,   26,   50,   19,   50,   22,    7,
        8,   19,    3,    4,   24,   23,   30,   29,   31,   39,
       35,   29,   30,   26,   26,   97,   31,   29,   35,   26,
       26,   29,   38,   31,   40,   51,   39,   31,   40,   51,

       38,   52,   52,   53,   53,   31,   38,   80,   89,   97,
      116,   38,  155,  175,  197,  320,  116,  314,  197,  313,
      312,  311,   89,  309,  307,  305,  304,  302,   80,  301,
      175,  300,  299,   80,  295,  294,  155,  317,  317,  317,
      318,  318,  318,  319,  319,  319,  321,  293,  321,  292,
      290,  287,  286,  284,  279,  278,  277,  276,  274,  273,
      272,  270,  269,  268,  267,  265,  263,  262,  259,  258,
      255,  254,  253,  252,  245,  244,  243,  242,  241,  239,
      238,  237,  236,  235,  234,  233,  232,  229,  228,  227,
      226,  225,  223,  222,  221,  220,  219,  218,  217,  216,

      214,  213,  212,  211,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  196,  195,  194,  192,  190,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  176,  174,  172,  171,  169,  167,  166,  164,  163,
      162,  160,  159,  157,  156,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  133,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  122,  120,  118,  117,  115,
      113,  112,  111,  110,  109,  108,  107,  106,  104,  103,
      102,  101,  100,   98,   96,   95,   94,   93,   92,   91,

       90,   88,   87,   86,   85,   84,   83,   82,   81,   79,
       78,   77,   76,   75,   74,   73,   72,   71,   70,   69,
       68,   67,   66,   65,   64,   63,   62,   61,   60,   59,
       58,   57,   56,   55,   49,   37,   36,   33,   32,   28,
       27,   25,    9,    6,    5,    2,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int pllolcode_yy_flex_debug;
int pllolcode_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *pllolcode_yytext;
#line 1 "scan.l"
#line 2 "scan.l"
#include "pllolcode_lang.h"
#include "pllolcode.h"
#include "postgres.h"
#include <string.h>
#include <stdlib.h>
#define LOL_LEX_DEBUG 1

#define YYSTACK_FREE pfree
#define YYSTACK_MALLOC palloc
#define YYFREE pfree
#define YYMALLOC palloc
#define YY_NO_INPUT

static YY_BUFFER_STATE scanbufhandle;
static char *scanbuf;

int  pllolcode_yylex(void);
void pllolcode_yyerror(char *);

/* These declarations get rid of compiler warnings */
FILE *pllolcode_yyget_in(void);
FILE *pllolcode_yyget_out(void);
int   pllolcode_yyget_leng(void);
char *pllolcode_yyget_text(void);
void  pllolcode_yyset_lineno(int);
int   pllolcode_yyget_lineno(void);
void  pllolcode_yyset_in(FILE *);
void  pllolcode_yyset_out(FILE *);
int   pllolcode_yyget_debug(void);
void  pllolcode_yyset_debug(int);
void  inline lol_lex_debug(char *s);

void pllolcode_scanner_init(const char *str);
void pllolcode_scanner_finish(void);

char *pllolcode_get_string_value(void);

int lineNumber = 0;

/* %option debug */



#line 711 "pllolcode_scan.c"

#define INITIAL 0
#define LOL_STRING 1
#define LOL_LINECOMMENT 2
#define LOL_BLOCKCMT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int pllolcode_yylex_destroy (void );

int pllolcode_yyget_debug (void );

void pllolcode_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE pllolcode_yyget_extra (void );

void pllolcode_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *pllolcode_yyget_in (void );

void pllolcode_yyset_in  (FILE * in_str  );

FILE *pllolcode_yyget_out (void );

void pllolcode_yyset_out  (FILE * out_str  );

int pllolcode_yyget_leng (void );

char *pllolcode_yyget_text (void );

int pllolcode_yyget_lineno (void );

void pllolcode_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int pllolcode_yywrap (void );
#else
extern int pllolcode_yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( pllolcode_yytext, pllolcode_yyleng, 1, pllolcode_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( pllolcode_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( pllolcode_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, pllolcode_yyin))==0 && ferror(pllolcode_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(pllolcode_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int pllolcode_yylex (void);

#define YY_DECL int pllolcode_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after pllolcode_yytext and pllolcode_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( pllolcode_yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(pllolcode_yytext[pllolcode_yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 52 "scan.l"

    /* todo: make this more robust (e.g. buffer length checking) */
    /* OLD STRING HANDLING
    char *stringptr = NULL; */

    /* Reworked string handling, copied from plpgsql */
    char *start_charpos = NULL;

#line 911 "pllolcode_scan.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! pllolcode_yyin )
			pllolcode_yyin = stdin;

		if ( ! pllolcode_yyout )
			pllolcode_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			pllolcode_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				pllolcode_yy_create_buffer(pllolcode_yyin,YY_BUF_SIZE );
		}

		pllolcode_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of pllolcode_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 317 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 347 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 60 "scan.l"
{ 
                /* TODO: Quit using stringbuf, use pllolcode_yytext. alloc a new char*
                 * for the contents and stick it in pllolcode_yyval.yarnVal */
                BEGIN LOL_STRING;
                start_charpos = pllolcode_yytext;
                /* OLD STRING HANDLING
                memset(stringbuf, 0, 255);
                stringptr = stringbuf; */
            }
	YY_BREAK
/* OLD STRING HANDLING : note that this decoding now happens in pllolcode_get_string
<LOL_STRING>\\n        { *stringptr++ = '\n'; }
<LOL_STRING>\\t        { *stringptr++ = '\t'; }
<LOL_STRING>\\\"    { *stringptr++ = '\"'; } */
case 2:
YY_RULE_SETUP
#line 73 "scan.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 74 "scan.l"
{ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 75 "scan.l"
{ lol_lex_debug("invalid string -- newline before closing quotes"); lineNumber++; exit(1); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 76 "scan.l"
{ 
                /* OLD STRING HANDLING
                *stringptr = 0;
                lol_lex_debug("pllolcode_yylex found string"); lol_lex_debug(stringbuf); */

                pllolcode_yyleng += (pllolcode_yytext - start_charpos);
                pllolcode_yytext = start_charpos;
                pllolcode_yylval.yarnVal = pllolcode_get_string_value();
                BEGIN 0;
                return YARN;
            }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 87 "scan.l"
{}
	YY_BREAK
/* OLD STRING HANDLING 
<LOL_STRING>.        { *stringptr++ = *pllolcode_yytext; } */
case 7:
YY_RULE_SETUP
#line 91 "scan.l"
{ BEGIN LOL_LINECOMMENT; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 92 "scan.l"
{ BEGIN 0; lol_lex_debug("pllolcode_yylex: line comment"); lineNumber++; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "scan.l"
{}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 95 "scan.l"
{ BEGIN LOL_BLOCKCMT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "scan.l"
{ BEGIN 0; lol_lex_debug("pllolcode_yylex: block comment"); }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 97 "scan.l"
{ lineNumber++; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "scan.l"
{}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "scan.l"
{ lol_lex_debug("pllolcode_yylex: HAI"); return HAI; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 101 "scan.l"
{ lol_lex_debug("pllolcode_yylex: KTHXBYE"); return KTHXBYE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 103 "scan.l"
{ lol_lex_debug("pllolcode_yylex: VISIBLE"); return VISIBLE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 104 "scan.l"
{ lol_lex_debug("pllolcode_yylex: VISDEBUG"); return VISDEBUG; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "scan.l"
{ lol_lex_debug("pllolcode_yylex: VISLOG"); return VISLOG; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "scan.l"
{ lol_lex_debug("pllolcode_yylex: VISNOTICE"); return VISNOTICE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "scan.l"
{ lol_lex_debug("pllolcode_yylex: VISINFO"); return VISINFO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "scan.l"
{ lol_lex_debug("pllolcode_yylex: VISWARNING"); return VISWARNING; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "scan.l"
{ lol_lex_debug("pllolcode_yylex: VISEXCEPTION"); return VISEXCEPTION; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 111 "scan.l"
{ lol_lex_debug("pllolcode_yylex: TROOFWIN"); return TROOFWIN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 112 "scan.l"
{ lol_lex_debug("pllolcode_yylex: TROOFFAIL"); return TROOFFAIL; }
	YY_BREAK
/* Arithmetic functions */
case 25:
YY_RULE_SETUP
#line 115 "scan.l"
{ lol_lex_debug("pllolcode_yylex: SUMOF"); return SUMOF; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 116 "scan.l"
{ lol_lex_debug("pllolcode_yylex: DIFFOF"); return DIFFOF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 117 "scan.l"
{ lol_lex_debug("pllolcode_yylex: PRODUKTOF"); return PRODUKTOF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 118 "scan.l"
{ lol_lex_debug("pllolcode_yylex: QUOSHUNTOF"); return QUOSHUNTOF; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 119 "scan.l"
{ lol_lex_debug("pllolcode_yylex: MODOF"); return MODOF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 120 "scan.l"
{ lol_lex_debug("pllolcode_yylex: BIGGROF"); return BIGGROF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 121 "scan.l"
{ lol_lex_debug("pllolcode_yylex: SMALLROF"); return SMALLROF; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 122 "scan.l"
{ lol_lex_debug("pllolcode_yylex: AN"); return AN; }
	YY_BREAK
/* Operators */
case 33:
YY_RULE_SETUP
#line 125 "scan.l"
{ lol_lex_debug("pllolcode_yylex: BOTHOF"); return BOTHOF; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 126 "scan.l"
{ lol_lex_debug("pllolcode_yylex: EITHEROF"); return EITHEROF; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 127 "scan.l"
{ lol_lex_debug("pllolcode_yylex: WONOF"); return WONOF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 128 "scan.l"
{ lol_lex_debug("pllolcode_yylex: NOT"); return NOT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 129 "scan.l"
{ lol_lex_debug("pllolcode_yylex: ALLOF"); return ALLOF; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 130 "scan.l"
{ lol_lex_debug("pllolcode_yylex: ANYOF"); return ANYOF; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 131 "scan.l"
{ lol_lex_debug("pllolcode_yylex: SMOOSH"); return SMOOSH; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 132 "scan.l"
{ lol_lex_debug("pllolcode_yylex: MKAY"); return MKAY; }
	YY_BREAK
/* Comparison */
case 41:
YY_RULE_SETUP
#line 135 "scan.l"
{ lol_lex_debug("pllolcode_yylex: BOTHSAEM"); return BOTHSAEM; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 136 "scan.l"
{ lol_lex_debug("pllolcode_yylex: DIFFRINT"); return DIFFRINT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 137 "scan.l"
{ lol_lex_debug("pllolcode_yylex: O RLY?"); return ORLY; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 138 "scan.l"
{ lol_lex_debug("pllolcode_yylex: YA RLY"); return YARLY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 139 "scan.l"
{ lol_lex_debug("pllolcode_yylex: NO WAI"); return NOWAI; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 140 "scan.l"
{ lol_lex_debug("pllolcode_yylex: MEBBE"); return MEBBE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 141 "scan.l"
{ lol_lex_debug("pllolcode_yylex: OIC"); return OIC; }
	YY_BREAK
/* Case */
case 48:
YY_RULE_SETUP
#line 144 "scan.l"
{ lol_lex_debug("pllolcode_yylex: WTF?"); return WTF; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 145 "scan.l"
{ lol_lex_debug("pllolcode_yylex: OMG"); return OMG; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 146 "scan.l"
{ lol_lex_debug("pllolcode_yylex: OMGWTF"); return OMGWTF; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 147 "scan.l"
{ lol_lex_debug("pllolcode_yylex: GTFO"); return GTFO; }
	YY_BREAK
/* Loop */
case 52:
YY_RULE_SETUP
#line 150 "scan.l"
{ lol_lex_debug("pllolcode_yylex: IM IN YR"); return IMINYR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 151 "scan.l"
{ lol_lex_debug("pllolcode_yylex: IM OUTTA YR"); return IMOUTTAYR; }
	YY_BREAK
/* Assignment, declaration */
case 54:
YY_RULE_SETUP
#line 154 "scan.l"
{ lol_lex_debug("pllolcode_yylex: IHASA"); return IHASA; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "scan.l"
{ lol_lex_debug("pllolcode_yylex: ITZ"); return ITZ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 156 "scan.l"
{ lol_lex_debug("pllolcode_yylex: R"); return R; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 157 "scan.l"
{ lol_lex_debug("pllolcode_yylex: FOUNDYR"); return FOUNDYR; }
	YY_BREAK
/* Casting */
case 58:
YY_RULE_SETUP
#line 160 "scan.l"
{ lol_lex_debug("pllolcode_yylex: MAEK"); return MAEK; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 161 "scan.l"
{ lol_lex_debug("pllolcode_yylex: ISNOWA"); return ISNOWA; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 162 "scan.l"
{ lol_lex_debug("pllolcode_yylex: A"); return A; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 163 "scan.l"
{ lol_lex_debug("pllolcode_yylex: TROOFTYPE"); return TROOFTYPE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 164 "scan.l"
{ lol_lex_debug("pllolcode_yylex: NUMBRTYPE"); return NUMBRTYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 165 "scan.l"
{ lol_lex_debug("pllolcode_yylex: NUMBARTYPE"); return NUMBARTYPE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 166 "scan.l"
{ lol_lex_debug("pllolcode_yylex: YARNTYPE"); return YARNTYPE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 167 "scan.l"
{ lol_lex_debug("pllolcode_yylex: NOOBTYPE"); return NOOBTYPE; }
	YY_BREAK
/* SPI */
case 66:
YY_RULE_SETUP
#line 170 "scan.l"
{ lol_lex_debug("pllolcode_yylex: GIMMEH"); return GIMMEH; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 171 "scan.l"
{ lol_lex_debug("pllolcode_yylex: OUTTADATABUKKIT"); return OUTTADATABUKKIT; }
	YY_BREAK
/* debugging commands */
case 68:
YY_RULE_SETUP
#line 174 "scan.l"
{ lol_lex_debug("pllolcode_yylex: YRVARZ"); return YRVARZ; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 176 "scan.l"
{ lol_lex_debug("pllolcode_yylex: IDENTIFIER"); return IDENTIFIER; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 177 "scan.l"
{
                    lol_lex_debug("pllolcode_yylex: NUMBR");
                    pllolcode_yylval.numbrVal = atoi(pllolcode_yytext);
                    return NUMBR;
                }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 182 "scan.l"
{
                    lol_lex_debug("pllolcode_yylex: NUMBAR");
                    pllolcode_yylval.numbarVal = strtod(pllolcode_yytext, NULL);
                    return NUMBAR;
                }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 188 "scan.l"
{ lineNumber++; }
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 189 "scan.l"
{ lol_lex_debug("EXPREND"); lineNumber++; return EXPREND; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 190 "scan.l"
;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 191 "scan.l"
{ pllolcode_yyerror("Parse error: Unrecognized character"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 192 "scan.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1421 "pllolcode_scan.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LOL_STRING):
case YY_STATE_EOF(LOL_LINECOMMENT):
case YY_STATE_EOF(LOL_BLOCKCMT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed pllolcode_yyin at a new source and called
			 * pllolcode_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = pllolcode_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( pllolcode_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * pllolcode_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of pllolcode_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					pllolcode_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			pllolcode_yyrestart(pllolcode_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) pllolcode_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 317 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 317 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 316);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					pllolcode_yyrestart(pllolcode_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( pllolcode_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve pllolcode_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void pllolcode_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        pllolcode_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            pllolcode_yy_create_buffer(pllolcode_yyin,YY_BUF_SIZE );
	}

	pllolcode_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	pllolcode_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void pllolcode_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		pllolcode_yypop_buffer_state();
	 *		pllolcode_yypush_buffer_state(new_buffer);
     */
	pllolcode_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	pllolcode_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (pllolcode_yywrap()) processing, but the only time this flag
	 * is looked at is after pllolcode_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void pllolcode_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	pllolcode_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE pllolcode_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) pllolcode_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pllolcode_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) pllolcode_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in pllolcode_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	pllolcode_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with pllolcode_yy_create_buffer()
 * 
 */
    void pllolcode_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		pllolcode_yyfree((void *) b->yy_ch_buf  );

	pllolcode_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a pllolcode_yyrestart() or at EOF.
 */
    static void pllolcode_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	pllolcode_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then pllolcode_yy_init_buffer was _probably_
     * called from pllolcode_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void pllolcode_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		pllolcode_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void pllolcode_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	pllolcode_yyensure_buffer_stack();

	/* This block is copied from pllolcode_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from pllolcode_yy_switch_to_buffer. */
	pllolcode_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void pllolcode_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	pllolcode_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		pllolcode_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void pllolcode_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)pllolcode_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pllolcode_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)pllolcode_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pllolcode_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE pllolcode_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) pllolcode_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pllolcode_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	pllolcode_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to pllolcode_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       pllolcode_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE pllolcode_yy_scan_string (yyconst char * yystr )
{
    
	return pllolcode_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to pllolcode_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE pllolcode_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) pllolcode_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in pllolcode_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = pllolcode_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in pllolcode_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pllolcode_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		pllolcode_yytext[pllolcode_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = pllolcode_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		pllolcode_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int pllolcode_yyget_lineno  (void)
{
        
    return pllolcode_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *pllolcode_yyget_in  (void)
{
        return pllolcode_yyin;
}

/** Get the output stream.
 * 
 */
FILE *pllolcode_yyget_out  (void)
{
        return pllolcode_yyout;
}

/** Get the length of the current token.
 * 
 */
int pllolcode_yyget_leng  (void)
{
        return pllolcode_yyleng;
}

/** Get the current token.
 * 
 */

char *pllolcode_yyget_text  (void)
{
        return pllolcode_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void pllolcode_yyset_lineno (int  line_number )
{
    
    pllolcode_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see pllolcode_yy_switch_to_buffer
 */
void pllolcode_yyset_in (FILE *  in_str )
{
        pllolcode_yyin = in_str ;
}

void pllolcode_yyset_out (FILE *  out_str )
{
        pllolcode_yyout = out_str ;
}

int pllolcode_yyget_debug  (void)
{
        return pllolcode_yy_flex_debug;
}

void pllolcode_yyset_debug (int  bdebug )
{
        pllolcode_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from pllolcode_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    pllolcode_yyin = stdin;
    pllolcode_yyout = stdout;
#else
    pllolcode_yyin = (FILE *) 0;
    pllolcode_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * pllolcode_yylex_init()
     */
    return 0;
}

/* pllolcode_yylex_destroy is for both reentrant and non-reentrant scanners. */
int pllolcode_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		pllolcode_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		pllolcode_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	pllolcode_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * pllolcode_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *pllolcode_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *pllolcode_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void pllolcode_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see pllolcode_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 192 "scan.l"



void lol_lex_debug(char *s) {
    if (LOL_LEX_DEBUG)
        elog(NOTICE, "%s", s);
}

int pllolcode_yywrap(void) {
    return 1;
}

char *pllolcode_get_string_value(void) {
    int len = 0;
    char *cp, *result;

    result = (char *) palloc(pllolcode_yyleng + 1);
    for (cp = pllolcode_yytext + 1; *cp; cp++) {
        if (*cp == '\\')
        {
            if (cp[1] == 'n') 
                result[len++] = '\n';
            else if (cp[1] == 't')
                result[len++] = '\t';
            else if (cp[1] == '"')
                result[len++] = '"';
            else if (cp[1] == '\\')
                result[len++] = '\\';
            cp++;
            /* Note that this code won't raise errors if you escape something invalid. TODO: Change that fact */
        }
        else if (*cp != '"') result[len++] = *cp;
    }
    result[len] = '\0';
    return result;
}

void pllolcode_scanner_init(const char *str) {
    /* More copying from PL/pgSQL */
    Size slen;
    slen = strlen(str);
/*    if (YY_CURRENT_BUFFER)
        pllolcode_yy_delete_buffer(YY_CURRENT_BUFFER); */
    scanbuf = palloc(slen + 2);
    memcpy(scanbuf, str, slen);
    scanbuf[slen] = scanbuf[slen + 1] = YY_END_OF_BUFFER_CHAR;
    scanbufhandle = pllolcode_yy_scan_buffer(scanbuf,slen + 2);

    BEGIN(INITIAL);
}

void
pllolcode_scanner_finish(void)
{
    pllolcode_yy_delete_buffer(scanbufhandle);
    pfree(scanbuf);
}

